### PR TITLE
Improved defcustoms.

### PR DESCRIPTION
**Pull request by PhilHudson**
Defcustoms now use correct :type stanzas.
Also some minor tweaks to markup and English idioms.

### CODE REVIEW

**Comment by PhilHudson** [comment]
Six months on... any interest?

**Comment by PhilHudson** [comment]
Someone? Anyone?

**Comment by mhayashi1120** [comment]
Thanks for the fix. very sorry for such late response.

**Comment by PhilHudson** [comment]
Please don't apologise, I know how it is. I'm thankful that you have
given us this useful tool. I only wish my contribution were greater.

**Pull request merged**
